config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  root to: 'homes#top'
  get '/about' => 'homes#about'
  resources :users
  resources :maps
  resources :spots
  resources :posts
  get '/plans/route' => 'plans#route'
  get '/plans/info' => 'plans#info'
  get '/plans/confirm' => 'plans#confirm'
  get '/plans/complete' => 'plans#complete'
  resources :plans do
    get 'join' => 'plans#join'
    get 'out' => 'plans#out'
    resource :group_chats
  end
  resources :places
  
end

app/models/user.rb
class User < ApplicationRecord
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :image
  has_many :posts, dependent: :destroy
  has_many :plans, dependent: :destroy
  has_many :plan_members, dependent: :destroy
  has_many :group_chats, dependent: :destroy
         
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
    end
  end
  
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id).page(params[:page]).per(4).order('id DESC')
    @entries = PlanMember.where(user_id: @user.id).page(params[:page]).per(4).order('id DESC')
  end
  
  def edit
    @user = User.find(params[:id])
    # 本人でないと編集ページに行けない
    if @user.id == current_user.id
      render "edit"
    else
      redirect_to users_path
    end
  end
  
  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path(current_user.id)
  end
  
  
  private
  
  def user_params
    params.require(:user).permit(:name,:introduction,:image)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container mt-5">
  <div class="w-50 mx-auto">
    <%= form_with model: @user, local: true do |f| %>
      <h3>編集フォーム</h3>
      <!-- ユーザ入力用テキストエリア -->
      <div class="form-group border-top pt-3">
        <%= f.label "プロフィール画像" %>
        <%= f.file_field :image, accept: "image/*", class: "form-control-file" %>
      </div>
      <div class="form-group">
        <%= f.label '名前' %>
        <%= f.text_field :name, class: "form-control", style: "width: 94%" %>
      </div>
      <div class="form-group">
        <%= f.label '紹介文' %>
        <%= f.text_area :introduction, rows: "3", class: "form-control", style: "width: 94%" %>
      </div>
      <div class="text-left">
        <%= f.submit "更新", class: "btn btn-outline-success mr-2", style: "width: 45%" %>
        <%= link_to "戻る", user_path(@user), class: "btn btn-outline-secondary ml-2", style: "width: 45%" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="mx-auto mt-5 mb-4">
  <h2 class="kiwi-kaku font-weight-bold" style= "color: #5c9291; letter-spacing: 0.12em;"><i class="fas fa-map-marker-alt"></i> ユーザー</h2>
</div>

<div class="card-list-container mx-auto d-flex flex-wrap border-top border-bottom pb-5 pt-4" style="width: 85%">
  <% @users.each do |user| %>
  <div class="card mx-auto mt-3 border-0" style="width: calc(100% / 4); background-color:rgba(0,0,0,0)">
    <div class="card-body mx-auto">
      <div class="row d-flex justify-content-center">
        <% if user.image.attached? %>
          <%= image_tag user.image, class: "rounded-circle mb-3", style: "max-width: 18vw; height: 18vw; object-fit: cover" %>
        <% else %>
          <%= image_tag asset_path('noimage.jpg'), class: "rounded-circle mb-3", style: "max-width: 100%; height: 18vw; object-fit: cover" %>
        <% end %>
      </div>
      <div class="row px-2">
        <div class="mx-auto text-center">
          <div class="my-1 text-center">
            <span class="h5 font-weight-bold"><%= link_to user.name, user_path(user), style: "color: #5c9291" %></span>
          </div>
          <span class="font-weight-bold">登録日：<%= user.created_at.strftime("%Y.%m.%d") %></span>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
<div class="d-flex justify-content-center mb-4 py-5">
  <span class="h5 font-weight-bold" style="color: #5c9291; color: #5c9291;">
    <i class="fas fa-map-marker-alt"></i> <%= link_to "共有マップに戻る", maps_path, data: {"turbolinks" => false}, style: "color: #5c9291; color: #5c9291; letter-spacing: 0.12em" %>
    </span>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row d-flex flex-column mt-5 w-50 mx-auto">
    <div class="mb-3">
      <span class="h2 font-weight-bold" style="color: #5c9291; letter-spacing: 0.12em;"><%= @user.name %></span>
    </div>
    <div class="d-flex justify-content-center border-top pt-5 pb-3">
      <% if @user.image.attached? %>
        <%= image_tag @user.image, class: "rounded-circle mb-3", style: "max-width: 50%; height: 16vw; object-fit: cover" %>
      <% else %>
        <%= image_tag asset_path('noimage.jpg'), class: "rounded-circle mb-3", style: "max-width: 50%; height: 16vw; object-fit: cover" %>
      <% end %>
    </div>
    <div class="mb-3">
      <span style="line-height: 4"><%= @user.introduction %></span>
    </div>
    <div class="mb-3 d-flex justify-content-end">
      <% if @user.id == current_user.id %>
        <span><i class="fas fa-edit"></i> <%= link_to "情報を編集する", edit_user_path(@user.id) %></span>
      <% end %>
    </div>
    <% unless @posts.count == 0 then %>
      <div class="mb-3 mt-3">
        <span class="h2 font-weight-bold" style="color: #5c9291; letter-spacing: 0.12em;">投稿記事</span>
      </div>
      <div class="card-list-container mx-auto d-flex flex-wrap border-top pb-3 pt-4" style="width: 100%">
        <% @posts.each do |pos| %>
          <div class="card mx-auto mt-3 border-0" style="width: calc(100% / 2); background-color:rgba(0,0,0,0)">
            <div class="card-body mx-auto">
              <div class="row d-flex justify-content-center">
                <% if pos.image.attached? %>
                  <%= image_tag pos.image, class: "rounded mb-3", style: "max-width: 18vw; height: 18vw; object-fit: cover" %>
                <% else %>
                  <%= image_tag asset_path('noimage.jpg'), class: "rounded mb-3", style: "max-width: 100%; height: 18vw; object-fit: cover" %>
                <% end %>
              </div>
              <div class="row px-2">
                <div class="w-100">
                  <span class="font-weight-bold"><%= pos.created_at.strftime("%Y.%m.%d") %></span>
                  <div class="my-1">
                    <span class="h5 font-weight-bold"><%= link_to pos.title, post_path(pos), style: "color: #5c9291" %></span>
                  </div>
                  <div class="w-100">
                    <span class="card-title"><i class="fas fa-map-marker-alt"></i> <%= pos.spot.name %></span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="d-flex justify-content-center mb-5">
        <%= paginate @posts %>
      </div>
    <% end %>
    
    <% unless @entries.count == 0 then %>
      <div class="mb-3 mt-3">
        <span class="h2 font-weight-bold" style="color: #5c9291; letter-spacing: 0.12em;">参加中の旅行</span>
      </div>
      <div class="card-list-container mx-auto d-flex flex-wrap border-top pb-3 pt-4" style="width: 100%">
        <% @entries.each do |entry| %>
          <div class="card mx-auto mt-3 border-0" style="width: calc(100% / 2); background-color:rgba(0,0,0,0)">
            <div class="card-body mx-auto">
              <div class="row d-flex justify-content-center">
                <% if entry.plan.image.attached? %>
                  <%= image_tag entry.plan.image, class: "rounded mb-3", style: "max-width: 18vw; height: 18vw; object-fit: cover" %>
                <% else %>
                  <%= image_tag asset_path('noimage.jpg'), class: "rounded mb-3", style: "max-width: 100%; height: 18vw; object-fit: cover" %>
                <% end %>
              </div>
              <div class="row px-2">
                <div class="w-100">
                  <span class="font-weight-bold"><%= entry.plan.created_at.strftime("%Y.%m.%d") %></span>
                  <div class="my-1">
                    <span class="h5 font-weight-bold"><%= link_to entry.plan.plan_name, plan_path(entry.plan), data: {"turbolinks" => false}, style: "color: #5c9291" %></span>
                  </div>
                  <div class="w-100">
                    <span><i class="far fa-user"></i> <%= link_to entry.plan.user.name, user_path(entry.plan.user.id) %></span>
                  </div>
                  <% if entry.plan.end_day.before? Date.today %>
                    <span class="font-weight-bold text-danger">この旅行は終了しています。</span>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="d-flex justify-content-center mb-5">
      <%= paginate @entries %>
    </div>
    <div class="d-flex justify-content-center border-top py-5">
      <span class="h5 font-weight-bold" style="color: #5c9291; color: #5c9291;">
        <i class="far fa-user"></i> <%= link_to "一覧に戻る", users_path, style: "color: #5c9291; color: #5c9291; letter-spacing: 0.12em" %>
      </span>
    </div>
  </div>
</div>