config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  root to: 'homes#top'
  get '/about' => 'homes#about'
  resources :users
  resources :maps
  resources :spots
  resources :posts
  get '/plans/route' => 'plans#route'
  get '/plans/info' => 'plans#info'
  get '/plans/confirm' => 'plans#confirm'
  get '/plans/complete' => 'plans#complete'
  resources :plans do
    get 'join' => 'plans#join'
    get 'out' => 'plans#out'
    resource :group_chats
  end
  resources :places
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<div class="container" style="height: 90%">
  <div class="row h-100">
    <div class="col-6 d-flex align-items-center">
      <div class="w-100 justify-content-center" style="text-align: center">
        <%= image_tag asset_path('main_logo.png'), size: "300x300", class: "mb-2" %>
        <h1 class="text-center text-dark kiwi_kaku">　旅を、共有しよう。</h1>
      </div>
    </div>
    <div class="col-6 d-flex flex-column justify-content-center">
      <div class="mb-3">
        <div class="border-bottom py-2 mb-4">
          <span class="h2 font-weight-bold" style="color: #5c9291; letter-spacing: 0.12em;">コンセプト</span>
        </div>
        <div>
          <p style="line-height: 2">走る。</p>
          <p style="line-height: 2">止まる。</p>
          <p style="line-height: 2">眺める。</p>
          <p style="line-height: 2">旅の記録を共有するサイト。</p>
        </div>
      </div>
      <div>
        <div class="border-bottom py-2 mb-4">
          <span class="h2 font-weight-bold" style="color: #5c9291; letter-spacing: 0.12em;">リンク</span>
        </div>
        <div class="mb-3 d-flex justify-content-center">
          <%= link_to "共有マップを見る", maps_path, data: {"turbolinks" => false}, class: "btn btn-outline-info mx-2", style: "width: 45%" %>
          <%= link_to "投稿一覧を見る", posts_path, class: "btn btn-outline-info mx-2", style: "width: 45%" %>
        </div>
        <div class="mb-3 d-flex justify-content-center">
          <%= link_to "情報を投稿する", new_spot_path, data: {"turbolinks" => false}, class: "btn btn-outline-secondary mx-2", style: "width: 45%" %>
          <%= link_to "旅行を企画する", plans_route_path, data: {"turbolinks" => false}, class: "btn btn-outline-secondary mx-2", style: "width: 45%" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container position-relative" style="height: 90%">
  <div class="row d-flex align-items-center" style="height: 100%; width: 100%">
    <div class="w-100 justify-content-center" style="text-align: center">
      <%= image_tag asset_path('main_logo.png'), size: "300x300", class: "mb-2" %>
      <h1 class="text-center text-dark kiwi_kaku">　旅を、共有しよう。</h1>
      <div class="mt-4">
        <% if user_signed_in? %>
          <%= link_to "このサイトについて", about_path, class: "btn btn-success mx-2" %>
        <% else %>
          <%= link_to "ゲストとしてログイン", users_guest_sign_in_path, method: :post, class: "btn btn-primary" %>
        <% end %>
        <br><br>
        <%= flash[:notice] %>
      </div><br>
    </div>
  </div>
</div>