config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  root to: 'homes#top'
  get '/about' => 'homes#about'
  resources :users
  resources :maps
  resources :spots
  resources :posts
  get '/plans/route' => 'plans#route'
  get '/plans/info' => 'plans#info'
  get '/plans/confirm' => 'plans#confirm'
  get '/plans/complete' => 'plans#complete'
  resources :plans do
    get 'join' => 'plans#join'
    get 'out' => 'plans#out'
    resource :group_chats
  end
  resources :places
  
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :info, presence: true
  
  has_one_attached :image
  belongs_to :user
  belongs_to :spot
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @posts = Post.all.order(id: "DESC").page(params[:page]).per(8)
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def edit
    @post = Post.find(params[:id])
    # 本人でないと編集ページに行けない
    if @post.user_id == current_user.id
      render "edit"
    else
      redirect_to posts_path
    end
  end
  
  def update
    pos = Post.find(params[:id])
    pos.score = Language.get_data(post_params[:info])
    pos.update(post_params)
    redirect_to post_path(pos.id)  
  end
  
  def destroy
    pos = Post.find(params[:id])
    pos.destroy
    redirect_to posts_path
  end
  
  
  private
  
  def post_params
    params.require(:post).permit(:title,:info,:image,:score)
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="container mt-5">
  <div class="w-50 mx-auto">
    <%= form_with model: @post, local: true do |f| %>
      <h3>編集フォーム</h3>
      <!-- ユーザ入力用テキストエリア -->
      <div class="form-group border-top pt-4">
        <%= f.label "写真" %>
        <%= f.file_field :image, accept: "image/*", class: "form-control-file" %>
      </div>
      <div class="form-group">
        <%= f.label 'タイトル' %>
        <%= f.text_field :title, class: "form-control", style: "width: 94%" %>
      </div>
      <div class="form-group border-bottom pb-4">
        <%= f.label 'スポット情報' %>
        <%= f.text_area :info, rows: "3", class: "form-control", style: "width: 94%" %>
      </div>
      <div class="text-left mt-4 mb-5">
        <%= f.submit "更新", class: "btn btn-outline-success mr-2", style: "width: 45%" %>
        <%= link_to "削除", post_path(@post.id), method: :delete, class: "btn btn-outline-danger ml-2", style: "width: 45%", "data-confirm" => "本当に削除しますか？" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="mx-auto mt-5 mb-4">
  <h2 class="kiwi-kaku font-weight-bold" style= "color: #5c9291; letter-spacing: 0.12em;"><i class="fas fa-map-marker-alt"></i> 投稿一覧</h2>
</div>

<div class="card-list-container mx-auto d-flex flex-wrap border-top border-bottom pb-4 pt-4" style="width: 85%">
  <% @posts.each do |pos| %>
  <div class="card mx-auto mt-3 border-0" style="width: calc(100% / 4); background-color:rgba(0,0,0,0)">
    <div class="card-body mx-auto">
      <div class="row d-flex justify-content-center">
        <% if pos.image.attached? %>
          <%= image_tag pos.image, class: "rounded mb-3", style: "max-width: 18vw; height: 18vw; object-fit: cover" %>
        <% else %>
          <%= image_tag asset_path('noimage.jpg'), class: "rounded mb-3", style: "max-width: 100%; height: 18vw; object-fit: cover" %>
        <% end %>
      </div>
      <div class="row px-2">
        <div class="w-100">
          <span class="font-weight-bold"><%= pos.created_at.strftime("%Y.%m.%d") %></span>
          <div class="my-1">
            <span class="h5 font-weight-bold"><%= link_to pos.title, post_path(pos), style: "color: #5c9291" %></span>
          </div>
          <div class="w-100">
            <span><i class="far fa-user"></i> <%= link_to pos.user.name, user_path(pos.user.id) %></span> | 
            <span class="card-title"><i class="fas fa-map-marker-alt"></i> <%= pos.spot.name %></span>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
<div class="d-flex justify-content-center mt-2">
  <%= paginate @posts %>
</div>
<div class="d-flex justify-content-center mb-4 py-5">
  <span class="h5 font-weight-bold" style="color: #5c9291; color: #5c9291;">
    <i class="fas fa-map-marker-alt"></i> <%= link_to "情報を投稿する", new_spot_path, data: {"turbolinks" => false}, style: "color: #5c9291; color: #5c9291; letter-spacing: 0.12em" %>
  </span>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row d-flex flex-column mt-5 w-50 mx-auto">
    <div class="mb-3">
      <span class="font-weight-bold"><%= @post.created_at.strftime("%Y.%m.%d") %></span> | 
      <span class="card-title font-weight-bold"><i class="fas fa-map-marker-alt"></i> <%= @post.spot.name %></span><br><br>
      <span class="h2 font-weight-bold" style="color: #5c9291; letter-spacing: 0.12em;"><%= @post.title %></span>
    </div>
    <div class="d-flex justify-content-center border-top pt-5 pb-3">
      <% if @post.image.attached? %>
        <%= image_tag @post.image, class: "rounded mb-3", style: "max-width: 100%; height: 33vw; object-fit: cover" %>
      <% else %>
        <%= image_tag asset_path('noimage.jpg'), class: "rounded mb-3", style: "max-width: 100%; height: 33vw; object-fit: cover" %>
      <% end %>
    </div>
    <div class="mb-3">
      <span style="line-height: 4"><%= @post.info %></span>
    </div>
    <div>
      <div class="bg-success float-right text-light text-center rounded px-2 mb-2" style="width:fit-content">
        <span>感情分析スコア</span><br>
        <span>点数：<%= @post.score %></span>
      </div>
    </div>
    <div class="mb-3 d-flex justify-content-end">
      <% if @post.user_id == current_user.id %>
        <span class="mr-3"><i class="fas fa-edit"></i> <%= link_to "記事を編集する", edit_post_path(@post.id) %></span>
        <span><i class="far fa-user"></i> <%= link_to @post.user.name, user_path(@post.user.id) %></span>
      <% else %>
        <span><i class="far fa-user"></i> <%= link_to @post.user.name, user_path(@post.user.id) %></span>
      <% end %>
    </div>
    <div class="d-flex justify-content-center border-top py-5">
      <span class="h5 font-weight-bold" style="color: #5c9291; color: #5c9291;"><i class="fas fa-map-marker-alt"></i> <%= link_to "投稿一覧に戻る", posts_path, style: "color: #5c9291; color: #5c9291; letter-spacing: 0.12em" %></span>
    </div>
  </div>
</div>