config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  root to: 'homes#top'
  get '/about' => 'homes#about'
  resources :users
  resources :maps
  resources :spots
  resources :posts
  get '/plans/route' => 'plans#route'
  get '/plans/info' => 'plans#info'
  get '/plans/confirm' => 'plans#confirm'
  get '/plans/complete' => 'plans#complete'
  resources :plans do
    get 'join' => 'plans#join'
    get 'out' => 'plans#out'
    resource :group_chats
  end
  resources :places
  
end

app/models/plan.rb
class Plan < ApplicationRecord
  
  validates :plan_name, presence: true
  validates :start_day, presence: true
  validates :end_day, presence: true
  validates :meeting_place, presence: true
  validates :meeting_time, presence: true
  
  has_one_attached :image
  belongs_to :user
  has_many :places, dependent: :destroy
  has_many :plan_members, dependent: :destroy
  has_many :group_chats, dependent: :destroy
  
  def member?(user)
    plan_members.where(user_id: user.id).exists?
  end
  
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  
  def index
    @plans = Plan.all.order(id: "DESC").page(params[:page]).per(8)
  end
  
  def show
    @plan = Plan.find(params[:id])
    
    @start_day = @plan.start_day
    @end_day = @plan.end_day
    @meeting_place = @plan.meeting_place
    @meeting_time = @plan.meeting_time
    @memo = @plan.memo
    
    @places = Place.where(plan_id: @plan.id)
    
    # 経由地名を配列化してjs用の変数に入れる
    @names = @places.pluck(:name)
    gon.spot_names = @names
    
    # 緯度を配列化してjs用の変数に入れる
    @lats = @places.pluck(:lat)
    gon.spot_lats = @lats
    
    # 経度を配列化してjs用の変数に入れる
    @lngs = @places.pluck(:lng)
    gon.spot_lngs = @lngs
    
    @members = PlanMember.where(plan_id: @plan.id)
  end
  
  def create
    # プランを投稿・保存
    @plan = Plan.new(plan_params)
    @plan.save
    
    # 同ユーザーの直近の投稿IDを取得(Planテーブル)
    plans = Plan.all.order(id: "DESC")
    plan = plans.find_by(user_id: current_user.id)
    
    # 各データの配列化
    @places = place_params
    names = @places[:place][:name].split
    lats = @places[:place][:lat].split
    lngs = @places[:place][:lng].split
    
    # 配列の要素数を取得(経由地の数)
    cnt = names.count
    
    # 各データをplaceモデルに保存
    for i in 1..(cnt) do
      @place = Place.new
      @place.plan_id = plan.id
      @place.name = names[i - 1]
      @place.lat = lats[i - 1]
      @place.lng = lngs[i - 1]
      @place.save
    end
    
    # 完了画面に遷移
    redirect_to plans_complete_path
  end
  
  def edit
    @plan = Plan.find(params[:id])
    # 本人でないと編集ページに行けない
    if @plan.user_id == current_user.id
      render "edit"
    else
      redirect_to plans_path
    end
  end
  
  def update
    plan = Plan.find(params[:id])
    plan.update(plan_params)
    redirect_to plan_path(plan.id)  
  end
  
  def destroy
    plan = Plan.find(params[:id])
    plan.destroy
    redirect_to plans_path
  end
  
  def route
    @plan = Plan.new
    @place = Place.new
  end
  
  def info
    # ルート情報がない場合はリダイレクト
    if params[:plan][:time] == "" then
      redirect_to plans_route_path, alert: '※ ルートが指定されていません'
    end
    @plan = Plan.new
  end
  
  def confirm
    # 保存用データを変数に入れる
    @plan = Plan.new
    @place = Place.new
    @start_day = params[:plan]['start_day(1i)'] + "-" + params[:plan]['start_day(2i)'] + "-" + params[:plan]['start_day(3i)']
    @end_day = params[:plan]['end_day(1i)'] + "-" + params[:plan]['end_day(2i)'] + "-" + params[:plan]['end_day(3i)']
    @meeting_place = params[:plan][:meeting_place]
    @meeting_time = params[:plan]['meeting_time(4i)'] + "：" + params[:plan]['meeting_time(5i)']
    @memo = params[:plan][:memo]
    
    # 経由地名を配列化してjs用の変数に入れる
    names = params[:plan][:spot_name]
    @spot_names = names.split(",")
    gon.spot_names = @spot_names
    
    # 緯度を配列化してjs用の変数に入れる
    lats = params[:plan][:spot_lat]
    @spot_lats = lats.split(",")
    gon.spot_lats = @spot_lats
    
    # 経度を配列化してjs用の変数に入れる
    lngs = params[:plan][:spot_lng]
    @spot_lngs = lngs.split(",")
    gon.spot_lngs = @spot_lngs
  end
  
  def complete
    # 同ユーザーの直近の投稿IDを取得(Planテーブル)
    plans = Plan.all.order(id: "DESC")
    plan = plans.find_by(user_id: current_user.id)
    @id = plan.id
    plan_member = PlanMember.new(user_id: current_user.id, plan_id: @id)
    plan_member.save
  end
  
  def join
    @plan_member = PlanMember.new(user_id: current_user.id, plan_id: params[:plan_id])
    @plan_member.save
    redirect_to plan_path(params[:plan_id])
  end
  
  def out
    @plan_member = PlanMember.find_by(user_id: current_user.id, plan_id: params[:plan_id])
    @plan_member.destroy
    redirect_to plan_path(params[:plan_id])
  end
  
  
  private
  
  def plan_params
    params.require(:plan).permit(:user_id,:plan_name,:start_day,:end_day,:meeting_place,:meeting_time,:memo,:image)
  end
  
  def place_params
    params.require(:plan).permit(place:[:name,:lat,:lng])
  end
  
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/complete.html.erb
<div class="container d-flex align-items-center h-100">
  <div class="mx-auto text-center">
    <span class="h1">企画を投稿しました</span><br><br>
    <%= link_to "企画ページを見る", plan_path(@id), data: {"turbolinks" => false}, class: "btn btn-outline-primary" %>
  </div>
</div>

app/views/plans/edit.html.erb
<div class="container mt-5">
  <div class="w-50 mx-auto">
    <%= form_with model: @plan, local: true do |f| %>
      <h3>編集フォーム</h3>
      <!-- ユーザ入力用テキストエリア -->
      <div class="form-group border-top pt-4">
        <%= f.label '企画名' %>
        <%= f.text_field :plan_name, class: "form-control", style: "width: 94%" %>
      </div>
      <div class="form-group">
        <%= f.label '出発日' %><br>
        <%= f.date_select :start_day, {}, {class: 'form-control', style: 'display: inline-block; width: auto;'} %>
      </div>
      <div class="form-group">
        <%= f.label '帰着日' %><br>
        <%= f.date_select :end_day, {}, {class: 'form-control', style: 'display: inline-block; width: auto;'} %>
      </div>
      <div class="form-group">
        <%= f.label '集合場所' %>
        <%= f.text_field :meeting_place, class: "form-control", style: "width: 94%" %>
      </div>
      <div class="form-group">
        <%= f.label '集合時間' %>
        <%= f.text_field :meeting_time, class: "form-control", style: "width: 94%" %>
      </div>
      <div class="form-group">
        <%= f.label '内容' %>
        <%= f.text_area :memo, rows: "3", class: "form-control", style: "width: 94%" %>
      </div>
      <div class="form-group border-bottom pb-4">
        <%= f.label "サムネイル" %>
        <%= f.file_field :image, accept: "image/*", class: "form-control-file" %>
      </div>
      <div class="text-left mt-4 mb-5">
        <%= f.submit "企画を更新", class: "btn btn-outline-success mr-2", style: "width: 45%" %>
        <%= link_to "企画を削除", plan_path(@plan.id), method: :delete, class: "btn btn-outline-danger ml-2", style: "width: 45%", "data-confirm" => "本当に削除しますか？" %>
      </div>
    <% end %>
  </div>
</div>

app/views/plans/index.html.erb
<div class="mx-auto mt-5 mb-4">
  <h2 class="kiwi-kaku font-weight-bold" style= "color: #5c9291; letter-spacing: 0.12em;"><i class="fas fa-calendar"></i> 旅行一覧</h2>
</div>

<div class="card-list-container mx-auto d-flex flex-wrap border-top border-bottom pb-4 pt-4" style="width: 85%">
  <% @plans.each do |plan| %>
  <div class="card mx-auto mt-3 border-0" style="width: calc(100% / 4); background-color:rgba(0,0,0,0)">
    <div class="card-body mx-auto">
      <div class="row d-flex justify-content-center">
        <% if plan.image.attached? %>
          <%= image_tag plan.image, class: "rounded mb-3", style: "max-width: 18vw; height: 18vw; object-fit: cover" %>
        <% else %>
          <%= image_tag asset_path('noimage.jpg'), class: "rounded mb-3", style: "max-width: 100%; height: 18vw; object-fit: cover" %>
        <% end %>
      </div>
      <div class="row px-2">
        <div class="w-100">
          <span class="font-weight-bold">[発]<%= plan.start_day.strftime("%Y.%m.%d") %></span> | 
          <span class="font-weight-bold">参加中：<%= plan.plan_members.count %>名</span>
          <div class="my-1">
            <span class="h5 font-weight-bold"><%= link_to plan.plan_name, plan_path(plan), data: {"turbolinks" => false}, style: "color: #5c9291" %></span>
          </div>
          <div class="w-100">
            <span><i class="far fa-user"></i> <%= link_to plan.user.name, user_path(plan.user.id) %></span>
          </div>
          <% if plan.end_day.before? Date.today %>
            <span class="font-weight-bold text-danger">この旅行は終了しています。</span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
<div class="d-flex justify-content-center">
  <%= paginate @plans %>
</div>
<div class="d-flex justify-content-center mb-4 py-5">
  <span class="h5 font-weight-bold" style="color: #5c9291; color: #5c9291;">
    <i class="fas fa-calendar"></i> <%= link_to "旅行を企画する", plans_route_path, data: {"turbolinks" => false}, style: "color: #5c9291; color: #5c9291; letter-spacing: 0.12em" %>
  </span>
</div>

app/views/plans/info.html.erb
<div class="container mt-3">
  <h3>旅行企画 | Step② - 情報入力</h3>
  <!-- スポット情報入力 -->
  <%= form_with model: @plan, url: plans_confirm_path, method: :get, local: true do |f| %>
  <div class="border-top pt-4">
    <table class="table table-borderless rounded text-center" style="background:rgba(212,220,218,0.4);">
      <tr>
        <th style="vertical-align: middle;">企画名 <span style="color: tomato">*</span></th>
        <td class="w-75"><%= f.text_field :plan_name, required: true, class: "form-control" %></td>
      </tr>
      <tr>
        <th style="vertical-align: middle;">期間 <span style="color: tomato">*</span></th>
        <td class="w-75">
          出発日：<%= f.date_select :start_day, {}, {class: 'form-control', style: 'display: inline-block; width: auto;'} %>
          <span>　-　</span>
          帰着日：<%= f.date_select :end_day, {}, {class: 'form-control', style: 'display: inline-block; width: auto;'} %>
        </td>
      </tr>
      <tr>
        <th style="vertical-align: middle;">集合場所 <span style="color: tomato">*</span></th>
        <td class="w-75"><%= f.text_field :meeting_place, required: true, class: "form-control" %></td>
      </tr>
      <tr>
        <th style="vertical-align: middle;">集合時間 <span style="color: tomato">*</span></th>
        <td class="w-75"><%= f.time_select :meeting_time, {}, {class: 'form-control', style: 'display: inline-block; width: auto;'} %></td>
      </tr>
      <tr>
        <th style="vertical-align: middle;">連絡事項</th>
        <td class="w-75"><%= f.text_area :memo, rows: "4", class: "form-control" %></td>
      </tr>
    </table>
    <%= f.hidden_field :spot_name, :value => params[:plan][:name] %>
    <%= f.hidden_field :spot_lat, :value => params[:plan][:lat] %>
    <%= f.hidden_field :spot_lng, :value => params[:plan][:lng] %>
    <div class="d-flex justify-content-center border-top mt-4 mb-5">
      <%= f.submit "Step③ - 確認画面 に進む", data: {"turbolinks" => false}, class: "btn btn-outline-secondary w-50 mt-3" %>
    </div>  
  </div>
  <% end %>
</div>

app/views/plans/show.html.erb
<div class="container">
  <div class="row d-flex flex-column mt-5 w-100 mx-auto">
    <div class="row mb-2 justify-content-between">
      <div>
        <span class="font-weight-bold">投稿日：<%= @plan.created_at.strftime("%Y.%m.%d") %></span><br>
        <span class="h2 font-weight-bold" style="color: #5c9291; letter-spacing: 0.12em; line-height: 1.5;"><%= @plan.plan_name %></span><br>
        <span>期間：<%= @start_day.strftime("%Y.%m.%d") %> 〜 <%= @end_day.strftime("%Y.%m.%d") %></span> | 
        <span>参加中：<%= @plan.plan_members.count %>名</span>
        <% if @plan.end_day.before? Date.today %>
          <br><span class="font-weight-bold text-danger">この旅行は終了しています。</span>
        <% end %>
      </div>
      <div class="d-flex align-items-center">
        <% if @plan.user_id == current_user.id %>
          <%= link_to "旅行を編集する", edit_plan_path(@plan.id), class: "w-100 btn btn-success" %>
        <% elsif @plan.member?(current_user) %>
          <%= link_to "この旅行から抜ける", plan_out_path(@plan.id), data: {"turbolinks" => false}, class: "w-100 btn btn-danger" %>
        <% else %>
          <%= link_to "この旅行に参加する", plan_join_path(@plan.id), data: {"turbolinks" => false}, class: "w-100 btn btn-primary" %>
        <% end %>
      </div>
    </div>
    
    <div class="row border-top py-4">
      <div class="col-3 d-flex justify-content-left">
        <% if @plan.image.attached? %>
          <%= image_tag @plan.image, class: "rounded", style: "max-width: 100%; height: 16vw; object-fit: cover" %>
        <% else %>
          <%= image_tag asset_path('noimage.jpg'), class: "rounded", style: "max-width: 100%; height: 16vw; object-fit: cover" %>
        <% end %>
      </div>
        
      <div class="col-9">
        <div class="form-inline">
          <div class="rounded px-3 py-1 text-center" style="width:fit-content; background-color: #d4dcda;">
            <span class="font-weight-bold">集合</span>
            <div class="h5">
              <span>
                <i class="fas fa-map-marker-alt"></i> <%= @meeting_place %>　
                <i class="fas fa-clock"></i> <%= @meeting_time %>
              </span> 
            </div>
          </div>
          <div class="ml-3">
            <% if @plan.member?(current_user) %>
              <%= link_to "グループチャットを開く", plan_group_chats_path(params[:id]), class: "btn btn-info" %>
            <% end %>
          </div>
        </div>
        <div class="mt-3">
          <span class="border-bottom">主催者からの連絡事項</span><br>
          <span class="rounded px-3 py-1 text-center" style="width:fit-content; background-color: #d4dcda; line-height: 2.5"><%= @memo %></span>
        </div>
      </div>
    </div>
    
    <div class="row border-top py-4">
      <div class="col-6">
        <div class="h-100 rounded" id='map'></div>
      </div>
      <div class="col-6">
        <div class="row">
          <!-- 経由地リスト -->
          <div class="col-6">
            <label>経由地リスト</label>
            <ul id="route-list" class="list-group"></ul>
          </div>
          <!-- 道のり -->
          <div class="col-6">
            <label>道のり - 時間</label>
            <ul id="route-info" class="list-group"></ul>
          </div>
        </div>
      </div>
    </div>
    
    <div class="mb-3 d-flex justify-content-end">
      <span><i class="far fa-user"></i> <%= link_to @plan.user.name, user_path(@plan.user.id) %></span>
    </div>
    
    <div class="border-top py-5">
      <span>参加者</span>
      <div class="form-inline">
        <% @members.each do |member| %>
          <div class="text-center mr-2" style="width:fit-content">
            <% if member.user.image.attached? %>
              <%= image_tag member.user.image, class: "rounded-circle", style: "max-width: 100%; height: 8vw; object-fit: cover" %>
            <% else %>
              <%= image_tag asset_path('noimage.jpg'), class: "rounded-circle", style: "max-width: 100%; height: 8vw; object-fit: cover" %>
            <% end %>
            <br><%= link_to member.user.name, user_path(member.user) %>
          </div>
        <% end %>
      </div>
    </div>
    
    <div class="d-flex justify-content-center border-top py-5">
      <span class="h5 font-weight-bold" style="color: #5c9291; color: #5c9291;"><i class="fas fa-calendar"></i> <%= link_to "企画一覧に戻る", plans_path, style: "color: #5c9291; color: #5c9291; letter-spacing: 0.12em" %></span>
    </div>
  </div>
</div>


<script>
  // codeAddressでも使用する為、mapを関数外で定義&geocoderも用意
  let map
  let geocoder
  let marker = [];
  let info_window = [];
  let mark_pos = [];
  
  // 確認画面表示時にマップ・経由地・ルート情報の表示
  window.onload = function initMap(){
    // geocoder初期化
    geocoder = new google.maps.Geocoder()
    
    // mapの初期位置設定(東京駅)
    // lat：経度 lng：緯度
    map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 35.68136165284377, lng: 139.76705995711325},
    // 地図の拡大率(大きいほど拡大 1〜21)
    zoom: 7
    });
    
    // マップ情報・ピンを表示
    for (let i = 0; i < gon.spot_names.length; i++) {
      // 入力を取得
      let inputAddress = gon.spot_names[i];
    
      // geocodingしたあとmapを移動
      geocoder.geocode( { 'address': inputAddress}, function(results, status) {
        if (status == 'OK') {
          // 変数に情報を入れる
          mark_pos[i] = results[0].geometry.location;
          
            // map.setCenterでmark_posの緯度経度に移動
            map.setCenter(mark_pos[i]);
    
    　　  　// google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
          marker[i] = new google.maps.Marker({
            map: map,
            position: mark_pos[i]
          });
          
          // 吹き出しに表示する内容(ボタンで経由地に追加)
          info_window[i] = new google.maps.InfoWindow({
            content: gon.spot_names[i]
          });
          
          // マーカー上に吹き出しが自動で出る
          info_window[i].open(map,marker[i]);
          
          // クリックしたら吹き出しをマーカ上に出す
          marker[i].addListener('click', function(){
            info_window[i].open(map,marker[i]);
          });
          
        } else {
          // エラー時の処理
          alert('該当結果がありませんでした：' + status);
        }
      });
    }
    
    // 経由地リストの表示
    for (let i = 0; i < gon.spot_names.length; i++) {
      var li = $('<li>', {
        text: gon.spot_names[i],
        "class": "list-group-item",
        "id": "route-item"
      });
      li.attr("data-lat", gon.spot_lats[i]); // data-latという属性にlatを入れる
      li.attr("data-lng", gon.spot_lngs[i]); // data-lngという属性にlngを入れる
      $('#route-list').append(li);      // idがroute-listの要素の一番後ろにliを追加
    }
    
    // ルート検索画面で表示したルートを再表示
    var points = $('#route-list li');
    var route_names = [];
    var route_lats = [];
    var route_lngs = [];
    
    // hidden_fieldにスポット位置情報を入れる (データ保存用)
    for (let i = 0; i < points.length; i++) {
      route_names[i] = points[i].textContent;
      route_lats[i] = document.getElementById('route-list').children[i].getAttribute('data-lat');
      route_lngs[i] = document.getElementById('route-list').children[i].getAttribute('data-lng');
      //document.getElementById('lng').value = pos_lng;
    }
  
    // 2地点以上の場合
    if (points.length >= 2){
      var origin;          // 開始地点
      var destination;     // 終了地点
      var waypoints = [];  // 経由地点
  
      // origin, destination, waypointsを設定する
      for (let i = 0; i < points.length; i++) {
          points[i] = new google.maps.LatLng($(points[i]).attr("data-lat"), $(points[i]).attr("data-lng"));
          if (i == 0){
            origin = points[i];
          } else if (i == points.length-1){
            destination = points[i];
          } else {
            waypoints.push({ location: points[i], stopover: true });
          }
      }
      
      // リクエストの作成
      var request = {
        origin:      origin,
        destination: destination,
        waypoints: waypoints,
        travelMode:  google.maps.TravelMode.DRIVING // 運転ルートで検索
      }
      
      // ルートサービスのリクエスト
      new google.maps.DirectionsService().route(request, function(response, status) {
        if (status == google.maps.DirectionsStatus.OK) {
          new google.maps.DirectionsRenderer({
            map: map,
            suppressMarkers : true
          }).setDirections(response);
          
          // 距離・時間を表示
          var data = response.routes[0].legs;
          var dist_sum = 0;
          var times = [];
          var hour_sum = 0;
          var minute_sum = 0;
          var time_sum = 0;
          
          for (let i = 0; i < data.length; i++) {
            // ルート検索したら道のり・時間を表示
            var info = $('<li>', {
              text: `${data[i].distance.text} - ${data[i].duration.text}`,
              "class": "list-group-item"
            });
            $('#route-info').append(info);  // idがroute-infoの要素の一番後ろに道のり情報を追加
            
            // 道のりの合計値を取得
            if (data[i].distance.text.includes('km')){
              // `km`単位でなければ加算しない(距離が近いと`m`で検索結果が出る)
              dist_sum += Math.round(parseFloat(data[i].distance.text) * 10) / 10;
            }
            
            // 時間の合計値を取得
            // 単位が`時間`か`分`かで計算を分ける
            if (data[i].duration.text.includes('時間')){
              times = data[i].duration.text.split('間');
              hour_sum += Math.round(parseFloat(times[0]));
              minute_sum += Math.round(parseFloat(times[1]));
            } else {
              minute_sum += Math.round(parseFloat(data[i].duration.text));
            }
            
            if (minute_sum > 59){
              hour_sum += Math.floor(minute_sum / 60);
              minute_sum = minute_sum % 60;
            }
            
            if (hour_sum == 0){
              time_sum = `${minute_sum}分`
            } else {
              time_sum = `${hour_sum}時間 ${minute_sum}分`
            }
            
            // 最後の繰り返し処理で行う事
            if (i == data.length - 1){
              info = $('<li>', {
                text: `合計：${dist_sum} km - ${time_sum}`,
                "class": "list-group-item"
              });
              $('#route-info').append(info);  // idがroute-infoの要素の一番後ろに合計を追加
              
              info = $('<li>', {
                text: `-`,
                "class": "list-group-item"
              });
              $('#route-info').prepend(info);  // idがroute-infoの要素の一番前に空の情報を追加
            }
          }
        }
      });
    }
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['SECRET_KEY'] %>&callback=initMap" async defer></script>